qnapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('questions.urls')),
    path('admin/', admin.site.urls),
]

questions/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import CustomLogoutView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.root_view, name='root'),
    path('question/list/', views.question_list, name='question_list'),
    path('home/', views.home, name='home'),

    path('question/<int:pk>/', views.question_detail, name='question_detail'),
    path('tag/<str:tag_name>/', views.filter_by_tag, name='filter_by_tag'),
    
    path('question/create/', views.manage_question, name='create_question'),
    path('question/<int:pk>/edit/', views.manage_question, name='edit_question'),
    path('question/<int:pk>/delete/', views.delete_question, name='delete_question'),
    path('question/<int:question_pk>/like/', views.like_question, name='like_question'),
    path('question/<int:question_pk>/unlike/', views.unlike_question, name='unlike_question'),

    path('question/<int:question_pk>/answer/', views.manage_answer, name='create_answer'),
    path('question/<int:question_pk>/answer/<int:answer_pk>/edit/', views.manage_answer, name='edit_answer'),
    path('question/<int:question_pk>/answer/<int:answer_pk>/delete/', views.delete_answer, name='delete_answer'),
    path('question/<int:question_pk>/answer/<int:answer_pk>/like/', views.like_answer, name='like_answer'),
    path('question/<int:question_pk>/answer/<int:answer_pk>/unlike/', views.unlike_answer, name='unlike_answer'),

    path('question/<int:question_pk>/comment/', views.handle_comment, name='create_comment'),
    path('question/<int:question_pk>/answer/<int:answer_pk>/comment/', views.create_comment_answer, name='create_comment_answer'),

    path('like_comment/<int:question_pk>/<int:comment_pk>/', views.like_comment, name='like_comment'),
    path('unlike_comment/<int:question_pk>/<int:comment_pk>/', views.unlike_comment, name='unlike_comment'),

    path('like_comment/<int:question_pk>/<int:answer_pk>/<int:comment_pk>/',views.like_comment, name='like_comment_answer'),
    path('unlike_comment/<int:question_pk>/<int:answer_pk>/<int:comment_pk>/',views.unlike_comment, name='unlike_comment_answer'),

    path('question/<int:question_pk>/answer/<int:answer_pk>/allcomments',views.question_answer_comment,name='question_answer_comment'),
      
    path('delete_comment/<int:question_pk>/<int:comment_pk>/', views.delete_comment, name='delete_comment'),
    path('edit_comment/<int:question_pk>/<int:comment_pk>/', views.handle_comment, name='edit_comment'),

    path('delete_comment/<int:question_pk>/<int:answer_pk>/<int:comment_pk>/',views.delete_comment, name='delete_comment_answer'),
    path('edit_comment/<int:question_pk>/<int:answer_pk>/<int:comment_pk>/',views.handle_comment, name='edit_comment_answer'),

    path('login/', views.custom_login, name='login'),
    # path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questions/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

class Question(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    tags = models.ManyToManyField(Tag, related_name='questions')
    created_at = models.DateTimeField(default=timezone.now,blank=True,null=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name='liked_question', blank=True)
    unlikes = models.ManyToManyField(User, related_name='unliked_question', blank=True)
    # images = models.ManyToManyField('Image', blank=True) 
    def save(self, *args, **kwargs):
        if not self.created_at:
            self.created_at = timezone.now()
        super().save(*args, **kwargs)
    def total_likes(self):
        return self.likes.count()

    def total_unlikes(self):
        return self.unlikes.count()
    
    def count_answers(self):
        return self.answers.count()

    def __str__(self):
        return self.title

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    likes = models.ManyToManyField(User, related_name='liked_answers')
    unlikes = models.ManyToManyField(User, related_name='unliked_answers')
    # images = models.ManyToManyField('Image', blank=True) 

   

    def count(self):
        question = Question.objects.get(id=self.id)
        return question.answers.count()

    def total_likes(self):
        return self.likes.count()

    def total_unlikes(self):
        return self.unlikes.count()

    def __str__(self):
        return self.description[:50]

class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE, related_name='comments')
    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE, related_name='comments')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='replies', null=True, blank=True)
    likes = models.ManyToManyField(User, related_name='liked_comments')
    unlikes = models.ManyToManyField(User, related_name='unliked_comments')

    def total_likes(self):
        return self.likes.count()

    def total_unlikes(self):
        return self.unlikes.count()

    def __str__(self):
        return self.content[:50]


class Image(models.Model):
    image = models.ImageField(upload_to='images/')
    created_at = models.DateTimeField(auto_now_add=True)

questions/forms.py
from django import forms
from .models import Question, Answer, Comment

# forms.py
from django import forms
from .models import Question, Tag

class QuestionForm(forms.ModelForm):
    new_tags = forms.CharField(
        required=False, 
        max_length=500, 
        label='New Tags', 
        help_text='Enter new tags separated by commas.'
    )
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Question
        fields = ['title', 'description', 'tags', 'created_at']
        widgets = {
            'created_at': forms.DateTimeInput(attrs={'type': 'datetime-local'})  # Customize input widget
        }

    def clean(self):
        cleaned_data = super().clean()
        new_tags = cleaned_data.get("new_tags")

        if new_tags:
            new_tags_list = [tag.strip() for tag in new_tags.split(',') if tag.strip()]
            existing_tags = Tag.objects.filter(name__in=new_tags_list)
            existing_tag_names = set(existing_tags.values_list('name', flat=True))
            new_tag_names = set(new_tags_list) - existing_tag_names

            # Create new tags
            for tag_name in new_tag_names:
                tag, created = Tag.objects.get_or_create(name=tag_name)
                cleaned_data['tags'] = list(cleaned_data['tags']) + [tag]

        return cleaned_data



class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['description']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

class TagFilterForm(forms.Form):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple
    )

questions/templates/questions/create_answer.html
{% extends "base_generic.html" %}
{% load custom_tags %}

{% block content %}
  <div class="max-w-4xl mx-auto mt-10 p-8 bg-white shadow-lg rounded-lg">
    <h1 class="text-3xl font-extrabold text-gray-900 mb-6">Add Your Answer</h1>
    
    <!-- Display question title and description -->
    <div class="bg-gray-100 p-4 rounded-md mb-6">
      <h2 class="text-xl font-semibold text-gray-800"> <span style="size: 10px; color: red;"> Q   </span>{{ question.title }}</h2>
      <!-- <p class="text-gray-700 mt-2"> description :{{ question.description }}</p> -->
      {% if question.description|length > 200 %}
            <p class="text-gray-700 mt-2">
                <span class="text-sm text-gray-400 p-1 mb-4">Description:</span>
                <span class="short-answer">{{ question.description|slice:":200" }}...</span>
                <span class="full-answer hidden">{{ question.description }}</span>
                <a href="javascript:void(0);" class="text-blue-500 hover:underline read-more">Read More</a>
            </p>
        {% else %}
            <p class="text-gray-700 mt-2 > <span class="text-sm text-gray-400 p-1 mb-4">Description:</span>{{ question.description }}</p>
        {% endif %}
    </div>
    
    <!-- Display form errors -->
    <!-- {% if form.errors %}
      <div class="mb-4">
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
          <strong class="font-bold">Oops!</strong>
          <span class="block sm:inline">Please fix the following errors:</span>
          <ul class="mt-2 list-disc list-inside">
            {% for field in form %}
              {% for error in field.errors %}
                <li>{{ field.label }}: {{ error }}</li>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        </div>
      </div>
    {% endif %} -->
    
    <!-- Answer form -->
    <form method="post" class="space-y-4" enctype="multipart/form-data">
      {% csrf_token %}
      
      <div class="mb-4">
        <label for="id_description" class="block text-gray-700 text-sm font-medium mb-2">Answer </label>
        {{ form.description|add_class:"shadow-sm border border-gray-300 rounded-md w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:ring-2 focus:ring-blue-500" }}
      </div>
      
      <div class="flex items-center justify-end">
        <button type="submit" class="bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-6 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500">
          Submit
        </button>
      </div>
    </form>
  </div>
  <script>
    document.addEventListener('DOMContentLoaded', function () {
        const readMoreLinks = document.querySelectorAll('.read-more');
    
        readMoreLinks.forEach(link => {
            link.addEventListener('click', function () {
                const shortAnswer = this.previousElementSibling;
                const fullAnswer = shortAnswer.previousElementSibling;
    
                shortAnswer.classList.toggle('hidden');
                fullAnswer.classList.toggle('hidden');
                this.textContent = this.textContent === 'Read More' ? 'Read Less' : 'Read More';
            });
        });
    
        const commentModal = document.getElementById('commentModal');
        const openCommentModal = document.getElementById('openCommentModal');
        const closeCommentModal = document.getElementById('closeCommentModal');
    
        openCommentModal.addEventListener('click', function () {
            commentModal.style.display = 'block';
        });
    
        closeCommentModal.addEventListener('click', function () {
            commentModal.style.display = 'none';
        });
    
        window.addEventListener('click', function (event) {
            if (event.target === commentModal) {
                commentModal.style.display = 'none';
            }
        });
    });
    </script>
{% endblock %}

questions/templates/questions/create_comment.html
{% extends "base_generic.html" %}
{% load static %}
{% load custom_tags %}

{% block content %}
  <div class="max-w-4xl mx-auto mt-10 p-8 bg-white shadow-md rounded-lg">
    <h1 class="text-2xl font-bold mb-6">
      {% if  answer_id %}
        <!-- <h2>Comment on Answer</h2> -->
         <span style="font-size: smaller; color:rgb(190, 208, 223);">Comment on Answer:</span>
        {% if answer.description|length > 200 %}
        <p class="mb-2">
            <span class="short-answer">{{ answer.description|slice:":200" }}...</span>
            <span class="full-answer hidden">{{ answer.description }}</span>
            <a href="javascript:void(0);" class="text-blue-500 hover:underline read-more">Read More</a>
        </p>
    {% else %}
        <p class="mb-2">{{ answer.description }}</p>
    {% endif %}
      {% else %}
      <span style="font-size: smaller; color:rgb(190, 208, 223);">Comment on Question:</span>
      <br>
      <span >{{ question.title}}</span>
        
      {% endif %}
    </h1>
    <form method="post">
      {% csrf_token %}
      <!-- Display form errors -->
      {% if form.errors %}
        <div class="mb-4">
          <ul class="text-red-600 list-disc list-inside">
            {% for field in form %}
              {% for error in field.errors %}
                <li>{{ field.label }}: {{ error }}</li>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        </div>
      {% endif %}
      <div class="mb-4">
        
        <label for="id_content" class="block text-gray-700 text-sm font-bold mb-2">Content</label>
        {{ form.content|add_class:"shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" }}
        <p class="text-gray-600 text-xs italic mt-1">{{ form.content.help_text }}</p>
      </div>
      <div class="flex items-center justify-between">
        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
          Submit Comment
        </button>
      </div>
    </form>
  </div>

  <script>
    document.addEventListener('DOMContentLoaded', function () {
        const readMoreLinks = document.querySelectorAll('.read-more');
    
        readMoreLinks.forEach(link => {
            link.addEventListener('click', function () {
                const shortAnswer = this.previousElementSibling;
                const fullAnswer = shortAnswer.previousElementSibling;
    
                shortAnswer.classList.toggle('hidden');
                fullAnswer.classList.toggle('hidden');
                this.textContent = this.textContent === 'Read More' ? 'Read Less' : 'Read More';
            });
        });
    });
    </script>
{% endblock %}

questions/templates/questions/create_question.html
{% extends "base_generic.html" %}
{% load custom_tags %}

{% block stylesheet %}
<style>
  .tag-grid {
    display: grid;
    grid-template-columns: repeat(10, 1fr); /* 10 columns with equal width */
    gap: 8px; /* Adjust spacing between items */
  }

  .tag-item {
    display: flex;
    align-items: center;
  }
</style>
{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
  <div class="max-w-4xl mx-auto mt-10 p-8 bg-white shadow-md rounded-lg">
    <h1 class="text-3xl font-bold mb-6">Ask a Question</h1>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <!-- Display form errors -->
       {% if form.errors %}
        <div class="mb-4">
          <ul class="text-red-600">
            {% for field in form %}
              {% for error in field.errors %}
                <li>{{ field.label }}: {{ error }}</li>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        </div>
      {% endif %} 
      <div class="mb-4">
        <label for="id_title" class="block text-gray-700 text-sm font-bold mb-2">Title</label>
        {{ form.title|add_class:"shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" }}
      </div>
      <div class="mb-4">
        <label for="id_description" class="block text-gray-700 text-sm font-bold mb-2">Description</label>
        {{ form.description|add_class:"shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" }}
      </div>
      <div class="mb-4">
        <label for="id_tags" class="block text-gray-700 text-sm font-bold mb-2">Tags</label>
        <div class="tag-grid">
          {% for tag in form.tags.field.queryset %}
            <div class="tag-item">
              <input type="checkbox" id="id_tags_{{ tag.id }}" name="tags" value="{{ tag.id }}" class="form-checkbox h-4 w-4 text-blue-600 transition duration-150 ease-in-out">
              <label for="id_tags_{{ tag.id }}" class="ml-2 text-gray-700 text-sm">{{ tag.name }}</label>
            </div>
          {% endfor %}
        </div>
        
      </div>
      <div class="mb-4">
        <label for="id_title" class="block text-gray-700 text-sm font-bold mb-2">Created at</label>
        {{ form.created_at|add_class:"shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" }}
      </div>
      

      <div class="mb-4">
        <label for="id_new_tags" class="block text-gray-700 text-sm font-bold mb-2">New Tags</label>
        {{ form.new_tags|add_class:"shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" }}
        <p class="text-gray-600 text-xs italic">{{ form.new_tags.help_text }}</p>
      </div>

      <!-- <div class="mb-4">
        <label for="id_images" class="block text-gray-700 text-sm font-bold mb-2">Images</label>
        <input 
            type="file" 
            name="images" 
            id="id_images" 
            multiple 
            class="hidden" 
            onchange="updateFileName()"
        />
        <label for="id_images" class="cursor-pointer bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
            Choose Files
        </label>
        <p id="file-name" class="text-gray-600 text-xs italic mt-2"></p>
        <p class="text-gray-600 text-xs italic">Upload images (you can select multiple files)</p>
    </div> -->

      <div class="flex items-center justify-between">
        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
          Submit
        </button>
      </div>
    </form>
  </div>
  {% else %}
  <script>
    window.location.href = "{% url 'login' %}?next={{ request.path }}";
  </script>
  {% endif %}

  <script>
    function updateFileName() {
        const input = document.getElementById('id_images');
        const fileName = input.files.length > 0 ? Array.from(input.files).map(file => file.name).join(', ') : 'No files chosen';
        document.getElementById('file-name').textContent = fileName;
    }
    </script>
{% endblock %}

questions/templates/questions/edit_comment.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Edit Comment</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save changes</button>
  </form>
{% endblock %}

questions/templates/questions/question_answer_comment.html
{% extends "base_generic.html" %}

{% block title %}{{ question.title }}{% endblock %}

{% block content %}
<div class="max-w-4xl mx-auto mt-8 p-4 bg-white shadow-md rounded-lg">
    <h2 class="text-2xl font-bold mb-4">Question: {{ question.title }}</h2>
    <div class="p-4 bg-gray-100 rounded-lg mb-6">
        <h2 class="text-xl font-semibold mb-2">Answer:</h2>
        <p class="text-gray-700">{{ answer.description }}</p>
    </div>

    <div class="mb-6">
        <h3 class="text-lg font-semibold mb-4">Comments:</h3>
        <ul class="space-y-4">
            {% for comment in comments %}
            <li class="p-4 bg-gray-100 rounded-lg shadow-sm">
                <p class="text-gray-700 mb-2">{{ comment.content }} - <span class="text-sm text-gray-500">{{ comment.user.username }} on {{ comment.created_at }}</span></p>
                <div class="flex items-center space-x-4">
                    <a href="{% url 'like_comment_answer' comment.answer.question.pk comment.answer.pk comment.pk %}" class="text-blue-500 hover:underline">👍 Upvote</a> <span  class="mx-2">{{ comment.total_likes }}</span> <span class="mx-2">|</span>
                    <a href="{% url 'unlike_comment_answer' comment.answer.question.pk comment.answer.pk comment.pk %}" class="text-red-500 hover:underline">👎 Downvote</a> <span  class="mx-2">{{ comment.total_unlikes }}</span><span class="mx-2">|</span>
                    {% if request.user == comment.user %}
                    <a href="{% url 'edit_comment_answer' comment.answer.question.pk comment.answer.pk comment.pk %}" class="text-green-500 hover:underline">✏️ Edit</a><span class="mx-2">|</span>
                    <a href="{% url 'delete_comment_answer' comment.answer.question.pk comment.answer.pk comment.pk %}" class="text-red-500 hover:underline">🗑️ Delete</a><span class="mx-2">|</span>
                    {% endif %}
                </div>
            </li>
            <!-- <li class="mb-6 p-4 bg-white shadow-md rounded-lg">
                <div class="flex items-center justify-between mb-2">
                    <div class="text-sm text-gray-500">Answered by {{ answer.user.username }} on {{ answer.created_at }}</div>
                </div>
                {% if answer.description|length > 200 %}
                    <p class="mb-2">
                        <span class="short-answer">{{ answer.description|slice:":200" }}...</span>
                        <span class="full-answer hidden">{{ answer.description }}</span>
                        <a href="javascript:void(0);" class="text-blue-500 hover:underline read-more">Read More</a>
                    </p>
                {% else %}
                    <p class="mb-2">{{ answer.description }}</p>
                {% endif %}
                <div class="flex justify-between items-center">
                    <div>
                        <a href="{% url 'like_answer' answer.question.pk answer.pk %}" class="text-blue-500 hover:underline">👍 Upvote</a> {{ answer.total_likes }}
                        <span class="mx-2">|</span>
                        <a href="{% url 'unlike_answer' answer.question.pk answer.pk %}" class="text-red-500 hover:underline">👎 Downvote</a> {{ answer.total_unlikes }}<span class="mx-2">|</span>
                        <a href="{% url 'question_answer_comment' answer.question.id answer.id %}" class="text-blue-500 hover:underline">Comments</a><span class="mx-2">|</span>
                        <a href="{% url 'create_comment_answer' answer.question.id answer.id %}" class="text-blue-500 hover:underline">Add Comment</a><span class="mx-2">|</span>
                    </div>
                    <div class="dropdown">
                        <span class="dropbtn">⋮</span>
                        <div class="dropdown-content">
                            {% if request.user == answer.user %}
                            <a href="{% url 'edit_answer' answer.question.pk answer.pk %}" class="text-green-500 hover:underline">✏️ Edit</a>
                            <a href="{% url 'delete_answer' answer.question.pk answer.pk %}" class="text-red-500 hover:underline">🗑️ Delete</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </li> -->
            {% endfor %}
        </ul>
    </div>

    <a href="{% url 'create_comment_answer' question.pk answer.pk %}" class="inline-block">
        <button type="submit" class="bg-blue-500 text-white py-2 px-4 rounded-lg hover:bg-blue-600 transition duration-300">Add Comment</button>
    </a>
</div>
{% endblock %}